"""Create tasks table

Revision ID: 926824852fbb
Revises: 
Create Date: 2026-05-15 14:29:35.249974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '926824852fbb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    # ### end Alembic commands ###
