FROM python:3.12-alpine

LABEL maintainer="xMattC"

ENV PYTHONUNBUFFERED=1

COPY ./requirements.txt /tmp/requirements.txt
COPY ./requirements.dev.txt /tmp/requirements.dev.txt
COPY . /web

WORKDIR /web
EXPOSE 8000

ARG DEV=false

RUN python -m venv /py && \
    /py/bin/pip install --upgrade pip && \
    apk add --update --no-cache postgresql-client && \
    apk add --update --no-cache --virtual .tmp-build-deps \
        build-base postgresql-dev musl-dev linux-headers && \
    /py/bin/pip install -r /tmp/requirements.txt && \
    if [ "$DEV" = "true" ]; then \
        /py/bin/pip install -r /tmp/requirements.dev.txt; \
    fi && \
    rm -rf /tmp && \
    apk del .tmp-build-deps && \
    adduser -D -H django-user && \
    mkdir -p /vol/web/static && \
    chown -R django-user:django-user /vol

ENV PATH="/py/bin:$PATH"

COPY ./scripts/run-django.sh /scripts/run-django.sh

RUN chmod +x /scripts/run-django.sh

EXPOSE 9000

USER django-user

CMD ["/scripts/run-django.sh"]