FROM python:3.12-alpine

LABEL maintainer="xMattC"

ENV PYTHONUNBUFFERED=1

COPY ./requirements.txt /tmp/requirements.txt
COPY ./requirements.dev.txt /tmp/requirements.dev.txt
COPY . /app
# COPY ./scripts/run-tasks.sh /scripts/run-tasks.sh

WORKDIR /app

EXPOSE 5000

ARG DEV=false

RUN python -m venv /py && \
    /py/bin/pip install --upgrade pip && \
    apk add --update --no-cache postgresql-client && \
    apk add --update --no-cache --virtual .tmp-build-deps \
        build-base postgresql-dev musl-dev && \
    /py/bin/pip install -r /tmp/requirements.txt && \
    if [ "$DEV" = "true" ]; then \
        /py/bin/pip install -r /tmp/requirements.dev.txt; \
    fi && \
    rm -rf /tmp && \
    apk del .tmp-build-deps && \
    # chmod +x /scripts/run-tasks.sh && \
    adduser -D -H flask-user

ENV PATH="/py/bin:$PATH"

USER flask-user

# CMD ["/scripts/run-tasks.sh"]