name: Web Checks

on:
  pull_request:
    paths:
      - "services/web/**"
      - "docker-compose.yml"
      - ".github/workflows/web-ci.yml"
  push:
    branches:
      - main
    paths:
      - "services/web/**"
      - "docker-compose.yml"
      - ".github/workflows/web-ci.yml"

jobs:
  web-check:
    name: Web Lint & Test
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test
        run: docker compose run --rm web sh -c "python manage.py wait_for_db && python manage.py test"

      - name: Lint
        run: docker compose run --rm web sh -c "flake8"